// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookSelectionController from "./book_selection_controller"
application.register("book-selection", BookSelectionController)

import CacheController from "./cache_controller"
application.register("cache", CacheController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LogChapterController from "./log_chapter_controller"
application.register("log-chapter", LogChapterController)

import TimeZoneController from "./time_zone_controller"
application.register("time-zone", TimeZoneController)
