// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import { Dropdown } from "tailwindcss-stimulus-components";
application.register('dropdown', Dropdown);

import CacheController from "./cache_controller"
application.register("cache", CacheController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LogChapterController from "./log_chapter_controller"
application.register("log-chapter", LogChapterController)
