production:
  reminder_notifications:
    class: SendRemindersJob
    schedule: every 15 minutes
  cleanup_finished_jobs:
    command: SolidQueue::Job.clear_finished_in_batches
    schedule: every day at 2am